<?xml version="1.0" encoding="utf-8"?><Database Name="Crossover" Class="CrossoverDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=Crossover;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CrossoverConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.application" Member="applications">
    <Type Name="application">
      <Column Name="application_id" Type="System.String" DbType="VarChar(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="display_name" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="secret" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Association Name="application_log" Member="logs" ThisKey="application_id" OtherKey="application_id" Type="log" />
    </Type>
  </Table>
  <Table Name="dbo.[log]" Member="logs">
    <Type Name="log">
      <Column Name="log_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="logger" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="[level]" Member="level" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="message" Type="System.String" DbType="VarChar(2048) NOT NULL" CanBeNull="false" />
      <Column Name="application_id" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Association Name="application_log" Member="application" ThisKey="application_id" OtherKey="application_id" Type="application" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
</Database>